# Generated by Django 3.1.3 on 2020-11-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page2',
        ),
    ]
