# Generated by Django 3.1.3 on 2020-11-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_delete_page2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
